# COMPONE DISTINTAS IMAGENES PARA QUE FUNCIONE EL SERVER
version: "3"

services: 
  web: 
    container_name: catalogueapp
    restart: always
    build: .
    ports:
      - "4000:3000"
    links: # enlace a otro container
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodatabase # contenedor de mongo
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none